### ISSUE TITLE
文档勘误：API 网关配置部分

### ISSUE THREAD

**Issue by ttimasdf** [serverless-components/tencent-flask#2]
文档中API网关对于HTTPS协议支持的写法是，`protocol: https` ，但实际上这行配置并不会生效，正确写法如下。

```yaml
    apigatewayConf:
      protocols:
        - http
        - https
      environment: release
```

ref:

https://github.com/serverless-components/tencent-flask/blob/cb6fcb458832dc3806aeb823ab1619089d6b7249/src/index.js#L87-L93
