### ISSUE TITLE
请问哪里设置绑定Layer

### ISSUE THREAD

**Issue by cloudwalkerfre** [serverless-components/tencent-flask#8]
比如像serverless-python-requirements里的
```
functions:
  hello:
    handler: handler.hello
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
```
我层压缩包已经传腾讯云上了，但是找不到这个tencent-flask绑定层设置的位置，是在functionconf下面么？
